server:
  port: 8005

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}   # 服务名称
        prefer-ip-address: true    # 是否注册ip

  application:
    name: consul-demo